import { OPERATORS } from "./Objects";

export const OPERATORS_ARRAY = [
    OPERATORS.ADD,
    OPERATORS.SUBTRACT,
    OPERATORS.MULTIPLY,
    OPERATORS.DIVIDE,
    OPERATORS.MODULUS,
    OPERATORS.EQUAL
]